# Dockerfile
#
# This docker-compose file contains the command to build a basic
# Apache container.
#
# Author: Kenny Carlile (KCarlile.com)
# Source: https://github.com/KCarlile/soundboard

version: '3.9'
services:
    kcarlile-httpd:
        build: .
        image: httpd:latest
        volumes:
            - ./:/var/www/html/
        container_name: soundboard-httpd
        ports:
            - 80:80
